name: deploy
on:
  workflow_dispatch:
permissions:
  contents: read
  deployments: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo deploy
